name: Documentation Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  doc-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the main branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Run documentation tests
        run: |
          rustup update --no-self-update
          cargo test --doc --release
        working-directory: docs
