name: Documentation Tests
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 7 * * 1'

jobs:
  doc-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the main branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          workspaces: docs

      - name: Run documentation tests
        run: |
          rustup update --no-self-update
          cargo test --doc --release -- --test-threads=1
        working-directory: docs

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: '❌ Documentation tests failed on ${{ github.ref }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
